let json: any = {
  'Merchandise Group Name': ['Beauty', 'Fashion', 'FG', 'SWT', 'WJA'],
  Data: {
    Beauty: {
      Makeup: {
        Foundations: [],
        Lipstick: [],
        Blushers: [],
        'Nail Enamel': [],
        'Makeup Accessories': [],
        Powder: [],
        'Makeup Mixed Sets': [],
        'Eye Color': [],
        Mascara: [],
      },
      Skincare: {
        Cleansers: [],
        Masks: [],
        'Eye Treatment': [],
        'Hair Products': [],
        Toners: [],
        'Face Moisturizers': [],
        'Repair Products': [],
        'Sun Products': [],
        'Body Products': [],
        'Skincare Mixed Sets': [],
        Serums: [],
        'Skincare Accessories': [],
      },
      Fragrances: {
        'Aftershave/Balm': [],
        'Room/Linen Sprays': [],
        Candles: [],
        Coffrets: [],
        'Hand Lotion': [],
        'Fragrance Singles': [],
        'Other Fragrance': [],
        Soap: [],
        'Body Moisturizer': [],
        'Fragrance Sets': [],
        'Home Accessories': [],
        'Fragrance Accessories': [],
        Deodorant: [],
        'Home Fragrance': [],
        Diffusers: [],
        'Bath & Shower': [],
      },
      'Beauty Accessories': {
        'Baby Bag': [],
        Backpack: [],
        Boston: [],
        'Bucket Bag': [],
        'Card Case': [],
        'Chain/Strap': [],
        Clutch: [],
        'Coin Purse': [],
        Continental: [],
        'Cosmetic Case': [],
        'Crossbody Bag': [],
        'Duffle Bag': [],
        'French Purse': [],
        Hobo: [],
        'Key Case': [],
        'Mini Handbag': [],
        'Passport Holder': [],
        Pouch: [],
        Satchel: [],
        'Shoulder Bag': [],
        'Tiny Bag': [],
        'Top Handle Bag': [],
        Tote: [],
        'Travel Organizer': [],
        'W Bras': [],
        'W One Piece Underwear': [],
        'W Panties': [],
        'W Undershirts': [],
        'W Waist Bag': [],
        Wristlet: [],
        'Zip Around': [],
        'Phone Cases': [],
        'Tech Accessories': [],
        'Tablet Cases': [],
        'W Pull Over Sweatshirts': [],
        'W Shorts': [],
        'W Sweatpants': [],
        'W Zip Up Sweatshirts': [],
        'Key Chains': [],
      },
      Fragrance: {
        Candles: [],
        Soap: [],
        'Fragrance Sets': [],
        'Aftershave/Balm': [],
        'Home Accessories': [],
        Coffrets: [],
        'Room/Linen Sprays': [],
        'Hand Lotion': [],
        'Fragrance Accessories': [],
        'Body Moisturizer': [],
        'Other Fragrance': [],
        Diffusers: [],
        'Fragrance Singles': [],
        'Bath & Shower': [],
        'Home Fragrance': [],
        Deodorant: [],
      },
    },
    Fashion: {
      RTW: {
        'M Wovens': [],
        'M Sweats': [],
        'W Wovens': [],
        'M Tee Shirts': [],
        'M Underwear': [],
        'M Sweaters': [],
        'M Outerwear': [],
        'W Underwear': [],
        'M Resortwear': [],
        'M Formalwear': [],
        'W Tee Shirts': [],
        'M Bottoms': [],
        'M Polo Shirts': [],
        'W Outerwear': [],
        'W Resortwear': [],
        'W Sweaters': [],
        'W Polo Shirts': [],
        'W Bottoms': [],
        'W Sweats': [],
        'W Dresses': [],
        'Kids Dresses': [],
        'Kids Bottoms': [],
        'Kids Underwear': [],
        'Kids Tee Shirts': [],
        'Kids Sweaters': [],
        'Kids Resortwear': [],
        'Kids Polo Shirts': [],
        'Kids Wovens': [],
        'Kids Outerwear': [],
        'Kids Sweats': [],
      },
      'Leather & Luggage': {
        MSLG: [],
        'M Belts': [],
        WLLG: [],
        MLLG: [],
        'W Belts': [],
        WSLG: [],
        Luggage: [],
        'Uni LLG': [],
        'Uni SLG': [],
      },
      Accessories: {
        Gifts: [],
        Gloves: [],
        'Hair Accessories': [],
        Hats: [],
        Scarves: [],
        Socks: [],
        'Tech Accessories': [],
        Ties: [],
        Umbrellas: [],
        'Neck Jewelry': [],
        'Wrist Jewelry': [],
        'Earrings & Head Jewelry': [],
        'Other Jewelry': [],
        Rings: [],
        'Travel Accessories': [],
        'Kids Sunglasses': [],
        'Uni Sunglasses': [],
        'W Sunglasses': [],
        'M Sunglasses': [],
        'Home Accessories': [],
        Stationery: [],
        Lighters: [],
        'Writing Instruments': [],
      },
      Shoes: {
        'W Sneakers': [],
        'W Sandals': [],
        'W Pumps': [],
        'W Flats': [],
        'W Boots': [],
        'W Drivers': [],
        'M Sneakers': [],
        'M Sandals': [],
        'M Shoes': [],
        'M Boots': [],
        'M Drivers': [],
        'Kids Sandals': [],
        'Kids Flats': [],
        'Kids Pumps': [],
        'Kids Drivers': [],
        'Kids Sneakers': [],
        'Kids Boots': [],
        'Footwear Accessories': [],
      },
      'ART DE TABLE': {
        TOWELS: [],
        'OTH PATTERNS': [],
        "THROWS PLUIE D'H": [],
        PAREO: [],
        'BABY COLLECTION': [],
        "CHAINE D'ANCRE": [],
        'OTH ITEMS': [],
        'THROWS DESIGN H': [],
        ASHTRAYS: [],
        SIESTA: [],
        RHYTHM: [],
        CANVAS: [],
        AFRICA: [],
        'BOLIDE TRAVEL CASE': [],
        'BLANKETS/THROWS': [],
        'ADV OTHER': [],
        'PICK UP ITEMS': [],
      },
      'BELTS KIT': {
        '13MM BUCKLES': [],
        '24MM STRAPS': [],
        '32MM BUCKLES': [],
        '42MM BUCKLES': [],
        '38MM STRAPS': [],
        '24MM BUCKLES': [],
        '32MM STRAPS': [],
        '13MM STRAPS': [],
        '38MM BUCKLES': [],
        '42MM STRAPS': [],
      },
      'BELTS STITCHED': {
        'OTHER BELTS': [],
        FASHION: [],
      },
      'CASHMERE SCARVES': {
        'OTHER CASHMERE': [],
        '70X70': [],
        '90X90': [],
        '140X140': [],
      },
      ENAMEL: {
        'CLIC H OTHER': [],
        'OTHER ENAMEL': [],
        BANGLES: [],
        'CLIC H BRAC': [],
        CHARNIERE: [],
        'CLIC CLAC H BRAC': [],
      },
      EQUITATION: {
        EQUITATION: [],
      },
      'FASHION JWL OTHER': {
        "CAGE D'H NECKLAC": [],
        'OTHER FASH JWL': [],
        HORN: [],
        'POP H NECKLACE': [],
      },
      'FEMME BAGS': {
        BOLIDE: [],
        'OTHER LLG': [],
        'BI-MATERIAL OTHER': [],
        JYPSIERE: [],
        'GARDEN PARTY': [],
        EVELYNE: [],
        LINDY: [],
        PICOTIN: [],
      },
      'FINE JEWELRY GOLD': {
        RINGS: [],
        'OTHER GOLD': [],
        NECKLACES: [],
        BRACELETS: [],
      },
      'FINE JEWELRY SILVER': {
        'GOLD/SILVER NECKLACES': [],
        'GOLD/SILVER OTHER': [],
        'GOLD/SILVER RINGS': [],
        'GOLD/SILVER BRACELETS': [],
        'SILVER BRACELETS': [],
        'SILVER NECKLACES': [],
        'SILVER RINGS': [],
        'SILVER OTHER': [],
      },
      'FRENCH FESTIVAL PRODUCT': {
        'FRENCH FESTIVAL PRODUCT': [],
      },
      GLOVES: {
        'GLOVE HOLDERS': [],
        GLOVES: [],
        HANKIES: [],
      },
      HATS: {
        HATS: [],
      },
      Horizon: {
        Others: [],
      },
      'LEATHER JEWELRY': {
        'OTHER LTHR JWL': [],
        'KELLY OTHER': [],
        HAPI: [],
        CDC: [],
        'KELLY DT': [],
        'KELLY DOG': [],
      },
      'MEMORY-KEEPERS': {
        REFILLS: [],
        COVER: [],
        'OTHER MEMORY': [],
      },
      MLLG: {
        'OTHER MLEATHER': [],
        BACKPACK: [],
        'MESSENGER BAG': [],
        BRIEFCASE: [],
      },
      MRTW: {
        KNITS: [],
        BOTTOMS: [],
        LEATHER: [],
        JACKETS: [],
        TEES: [],
        POLO: [],
        'WOVEN SHIRTS': [],
        'OTHER MRTW': [],
      },
      MSHOES: {
        ATHLETIC: [],
        'OTHER MSHOES': [],
      },
      'OTHER MENS SILK': {
        LOSANGE: [],
        POCHETTE: [],
        MUFFLERS: [],
        'MISC OTHER': [],
        BRODERIE: [],
      },
      'OTHER WOMENS SILK': {
        MOUSSELINE: [],
        'EX-LIBRIS': [],
        GAVROCHE: [],
        'SMALL TWILLY': [],
        'MISC OTHER': [],
        'MAXI TWILLY': [],
        JERSEY: [],
        BRODERIE: [],
        TWILLON: [],
      },
      PARFUM: {
        'JARDIN SUR LE TOIT': [],
        'EAU DES MERVEILLES': [],
        'CLASSICS COLLECTION': [],
        SOAPS: [],
        "JOUR D'HERMES": [],
        "TERRE D'HERMES": [],
        HERMESSENCE: [],
        'JARDIN MONSIEUR LI': [],
        'COLOGNES COLLECTION': [],
        "VOYAGE D'HERMES": [],
        'OTHER FRAGRANCE': [],
        'BATH LINE': [],
        'JARDIN SUR LE NIL': [],
        'XMAS SETS': [],
        'LOCKS/REFILLS': [],
        'TRAVEL RETAIL SETS': [],
        'LEATHER CASES/REFILL': [],
        "TWILLY D'HERMES": [],
        'JARDIN SUR LA LAGUNE': [],
      },
      'SCARF RINGS': {
        'SCARF RINGS': [],
      },
      SLG: {
        'BEARN COLLECTION': [],
        'WALLETS OTHER': [],
        'KEY OTHER': [],
        'MISC OTHER': [],
        'MENS & MC2': [],
        'KELLY COLLECTION': [],
        'DOGON COLLECTION': [],
      },
      TIES: {
        'PRINTED CLASSIC': [],
        'WOVEN OTHER': [],
        'WOVEN FACONNEE': [],
        'WOVEN HEAVY SILK': [],
        'PRINTED FANTASY TWILL': [],
        'PRINTED OTHER TIES': [],
        'PRINTED HEAVY TWILL': [],
      },
      'TWILL SCARVES': {
        '70X70 TWILL': [],
        '140X140 TWILL': [],
        '90X90 TWILL': [],
      },
      VOYAGE: {
        VOYAGE: [],
      },
      WATCH: {
        'NON PRECIOUS WOMENS': [],
        'PRECIOUS MENS': [],
        'NON PRECIOUS MEN': [],
        'OTHER WATCH': [],
        'PRECIOUS WOMENS': [],
        STRAPS: [],
      },
      WRTW: {
        'OTHER WRTW': [],
        LEATHER: [],
        TEES: [],
        'OUTERWEAR/JACKETS': [],
        'KNIT TOPS': [],
        'SCARF PRINT TOPS': [],
        'WOVEN BLOUSES': [],
        PANTS: [],
        SKIRTS: [],
      },
      WSHOES: {
        SANDALS: [],
        ATHLETIC: [],
        'OTHER WSHOES': [],
      },
      'Leather and Luggage': {
        Luggage: [],
        MSLG: [],
      },
      Skincare: {
        'Sun Products': [],
        'Body Products': [],
        Cleansers: [],
        'Skincare Accessories': [],
        Serums: [],
        Toners: [],
        'Eye Treatment': [],
        'Face Moisturizers': [],
        'Skincare Mixed Sets': [],
        Masks: [],
        'Repair Products': [],
        'Hair Products': [],
      },
      Fragrances: {
        'Room/Linen Sprays': [],
        'Body Moisturizer': [],
        Coffrets: [],
        'Other Fragrance': [],
        'Bath & Shower': [],
        'Fragrance Accessories': [],
        'Hand Lotion': [],
        'Fragrance Singles': [],
        Deodorant: [],
        'Fragrance Sets': [],
        Diffusers: [],
        Soap: [],
        'Home Accessories': [],
        'Aftershave/Balm': [],
        Candles: [],
        'Home Fragrance': [],
      },
      Makeup: {
        Lipstick: [],
        Blushers: [],
        'Eye Color': [],
        'Makeup Accessories': [],
        'Makeup Mixed Sets': [],
        'Nail Enamel': [],
        Powder: [],
        Mascara: [],
        Foundations: [],
      },
    },
    FG: {
      Food: {
        'Baked Goods': [],
        Sweets: [],
        Nuts: [],
        'Fruits/Vegetables/Flowers': [],
        Coffee: [],
        Condiments: [],
        Tea: [],
        'Other Food': [],
        'Food Accessories': [],
        Seafood: [],
        Beverages: [],
        Meat: [],
        Wellbeing: [],
        Chocolate: [],
      },
      Gifts: {
        Toys: [],
        'Travel Accessories': [],
        'Earrings & Head Jewelry': [],
        'Hair Accessories': [],
        'Neck Jewelry': [],
        'Other Jewelry': [],
        Rings: [],
        Socks: [],
        'Tech Accessories': [],
        Ties: [],
        Umbrellas: [],
        'Wrist Jewelry': [],
        Gloves: [],
        Hats: [],
        'Kids Boots': [],
        'Kids Bottoms': [],
        'Kids Dresses': [],
        'Kids Drivers': [],
        'Kids Flats': [],
        'Kids Outerwear': [],
        'Kids Polo Shirts': [],
        'Kids Pumps': [],
        'Kids Resortwear': [],
        'Kids Sandals': [],
        'Kids Sneakers': [],
        'Kids Sweaters': [],
        'Kids Sweats': [],
        'Kids Tee Shirts': [],
        'Kids Underwear': [],
        'Kids Wovens': [],
        Luggage: [],
        'M Belts': [],
        'M Boots': [],
        'M Bottoms': [],
        'M Drivers': [],
        'M Outerwear': [],
        'M Polo Shirts': [],
        'M Resortwear': [],
        'M Sandals': [],
        'M Shoes': [],
        'M Sneakers': [],
        'M Sweaters': [],
        'M Sweats': [],
        'M Tee Shirts': [],
        'M Underwear': [],
        'M Wovens': [],
        MLLG: [],
        MSLG: [],
        Scarves: [],
        'Uni LLG': [],
        'Uni SLG': [],
        'W Belts': [],
        'W Boots': [],
        'W Bottoms': [],
        'W Dresses': [],
        'W Drivers': [],
        'W Flats': [],
        'W Outerwear': [],
        'W Polo Shirts': [],
        'W Pumps': [],
        'W Resortwear': [],
        'W Sandals': [],
        'W Sneakers': [],
        'W Sweaters': [],
        'W Sweats': [],
        'W Tee Shirts': [],
        'W Underwear': [],
        'W Wovens': [],
        WLLG: [],
        WSLG: [],
        Fragrances: [],
        Skincare: [],
        'Home Accessories': [],
        'Other Souvenirs': [],
        Handcrafts: [],
        Gifts: [],
        Lighters: [],
        Stationery: [],
        'Writing Instruments': [],
        'M Formalwear': [],
        Makeup: [],
      },
    },
    SWT: {
      Spirits: {
        Vodka: [],
        Tequila: [],
        Rum: [],
        'Other Spirits': [],
        'Spirits Accessories': [],
        'American Whiskey': [],
        Baijiu: [],
        Gin: [],
        Beer: [],
        Liqueurs: [],
        Sake: [],
        'Other Whiskey': [],
        Scotch: [],
        'Single Malt': [],
        Brandy: [],
      },
      'Commercial Wine': {
        Australia: [],
        USA: [],
        Italy: [],
        France: [],
        'Other Wine': [],
        'South Africa': [],
        'New Zealand': [],
        'South America': [],
        'Other Europe': [],
        'Wine Accessories': [],
      },
      'Prestige Wine': {
        'Prestige France': [],
        'Prestige Other': [],
        'Prestige USA': [],
        'Prestige New Zealand': [],
        'Prestige Australia': [],
        'Prestige Italy': [],
      },
      Cigars: {
        Cigarillos: [],
        Accessories: [],
        'Hand Made': [],
        'Machine Made': [],
      },
      Tobacco: {
        'Filter Cigarette': [],
        'Non-Filter Tobacco': [],
        'Tobacco Accessories': [],
      },
    },
    WJA: {
      Accessories: {
        'Uni SLG': [],
        'Uni LLG': [],
        'M Belts': [],
        MSLG: [],
        MLLG: [],
        'W Belts': [],
        Luggage: [],
        WSLG: [],
        WLLG: [],
        'Writing Instruments': [],
        'Tech Accessories': [],
        Gifts: [],
        Lighters: [],
        Scarves: [],
        'Watch Accessories': [],
        Ties: [],
        'Hair Accessories': [],
        'Uni Sunglasses': [],
        'W Sunglasses': [],
        'Kids Sunglasses': [],
        'M Sunglasses': [],
        Stationery: [],
        'Home Accessories': [],
        Hats: [],
        Socks: [],
        'Travel Accessories': [],
        Umbrellas: [],
        Gloves: [],
      },
      Jewelry: {
        'Wrist Jewelry': [],
        'Bridal Jewelry': [],
        'Other Jewelry': [],
        'Earrings & Head Jewelry': [],
        'Neck Jewelry': [],
        Rings: [],
      },
      Watches: {
        'W Watches': [],
        'Uni Watches': [],
        'M Watches': [],
      },
    },
  },
  Data1: {
    Beauty: {},
    Fashion: {},
    FG: {},
    SWT: {},
    WJA: {},
  },
};

export const l1Categories = json;
