export interface L1Categories {
  l1_name: string;
  sub: boolean;
  l2_categories?: {
    l2_name: string;
    list: string[];
    desc?: string[];
  }[];
}

export const l1Categories: L1Categories[] = [
  {
    l1_name: 'Beauty',
    sub: true,
    l2_categories: [
      {
        l2_name: 'Makeup',
        list: [
          'Foundations',
          'Lipstick',
          'Blushers',
          'Nail Enamel',
          'Makeup Accessories',
          'Powder',
          'Makeup Mixed Sets',
          'Eye Color',
          'Mascara',
        ],
      },
      {
        l2_name: 'Skincare',
        list: [
          'Cleansers',
          'Masks',
          'Eye Treatment',
          'Hair Products',
          'Toners',
          'Face Moisturizers',
          'Repair Products',
          'Sun Products',
          'Body Products',
          'Skincare Mixed Sets',
          'Serums',
          'Skincare Accessories',
        ],
      },
      {
        l2_name: 'Fragrances',
        list: [
          'Aftershave/Balm',
          'Room/Linen Sprays',
          'Candles',
          'Coffrets',
          'Hand Lotion',
          'Fragrance Singles',
          'Other Fragrance',
          'Soap',
          'Body Moisturizer',
          'Fragrance Sets',
          'Home Accessories',
          'Fragrance Accessories',
          'Deodorant',
          'Home Fragrance',
          'Diffusers',
          'Bath & Shower',
        ],
      },
      {
        l2_name: 'Beauty Accessories',
        list: [
          'Baby Bag',
          'Backpack',
          'Boston',
          'Bucket Bag',
          'Card Case',
          'Chain/Strap',
          'Clutch',
          'Coin Purse',
          'Continental',
          'Cosmetic Case',
          'Crossbody Bag',
          'Duffle Bag',
          'French Purse',
          'Hobo',
          'Key Case',
          'Mini Handbag',
          'Passport Holder',
          'Pouch',
          'Satchel',
          'Shoulder Bag',
          'Tiny Bag',
          'Top Handle Bag',
          'Tote',
          'Travel Organizer',
          'W Bras',
          'W One Piece Underwear',
          'W Panties',
          'W Undershirts',
          'W Waist Bag',
          'Wristlet',
          'Zip Around',
          'Phone Cases',
          'Tech Accessories',
          'Tablet Cases',
          'W Pull Over Sweatshirts',
          'W Shorts',
          'W Sweatpants',
          'W Zip Up Sweatshirts',
          'Key Chains',
        ],
      },
      {
        l2_name: 'Fragrance',
        list: [
          'Candles',
          'Soap',
          'Fragrance Sets',
          'Aftershave/Balm',
          'Home Accessories',
          'Coffrets',
          'Room/Linen Sprays',
          'Hand Lotion',
          'Fragrance Accessories',
          'Body Moisturizer',
          'Other Fragrance',
          'Diffusers',
          'Fragrance Singles',
          'Bath & Shower',
          'Home Fragrance',
          'Deodorant',
        ],
      },
    ],
  },
  {
    l1_name: 'Fashion',
    sub: true,
    l2_categories: [
      {
        l2_name: 'RTW',
        list: [
          'M Wovens',
          'M Sweats',
          'W Wovens',
          'M Tee Shirts',
          'M Underwear',
          'M Sweaters',
          'M Outerwear',
          'W Underwear',
          'M Resortwear',
          'M Formalwear',
          'W Tee Shirts',
          'M Bottoms',
          'M Polo Shirts',
          'W Outerwear',
          'W Resortwear',
          'W Sweaters',
          'W Polo Shirts',
          'W Bottoms',
          'W Sweats',
          'W Dresses',
          'Kids Dresses',
          'Kids Bottoms',
          'Kids Underwear',
          'Kids Tee Shirts',
          'Kids Sweaters',
          'Kids Resortwear',
          'Kids Polo Shirts',
          'Kids Wovens',
          'Kids Outerwear',
          'Kids Sweats',
        ],
      },
      {
        l2_name: 'Leather & Luggage',
        list: [
          'MSLG',
          'M Belts',
          'WLLG',
          'MLLG',
          'W Belts',
          'WSLG',
          'Luggage',
          'Uni LLG',
          'Uni SLG',
        ],
      },
      {
        l2_name: 'Accessories',
        list: [
          'Gifts',
          'Gloves',
          'Hair Accessories',
          'Hats',
          'Scarves',
          'Socks',
          'Tech Accessories',
          'Ties',
          'Umbrellas',
          'Neck Jewelry',
          'Wrist Jewelry',
          'Earrings & Head Jewelry',
          'Other Jewelry',
          'Rings',
          'Travel Accessories',
          'Kids Sunglasses',
          'Uni Sunglasses',
          'W Sunglasses',
          'M Sunglasses',
          'Home Accessories',
          'Stationery',
          'Lighters',
          'Writing Instruments',
        ],
      },
      {
        l2_name: 'Shoes',
        list: [
          'W Sneakers',
          'W Sandals',
          'W Pumps',
          'W Flats',
          'W Boots',
          'W Drivers',
          'M Sneakers',
          'M Sandals',
          'M Shoes',
          'M Boots',
          'M Drivers',
          'Kids Sandals',
          'Kids Flats',
          'Kids Pumps',
          'Kids Drivers',
          'Kids Sneakers',
          'Kids Boots',
          'Footwear Accessories',
        ],
      },
      {
        l2_name: 'ART DE TABLE',
        list: [
          'TOWELS',
          'OTH PATTERNS',
          "THROWS PLUIE D'H",
          'PAREO',
          'BABY COLLECTION',
          "CHAINE D'ANCRE",
          'OTH ITEMS',
          'THROWS DESIGN H',
          'ASHTRAYS',
          'SIESTA',
          'RHYTHM',
          'CANVAS',
          'AFRICA',
          'BOLIDE TRAVEL CASE',
          'BLANKETS/THROWS',
          'ADV OTHER',
          'PICK UP ITEMS',
        ],
      },
      {
        l2_name: 'BELTS KIT',
        list: [
          '13MM BUCKLES',
          '24MM STRAPS',
          '32MM BUCKLES',
          '42MM BUCKLES',
          '38MM STRAPS',
          '24MM BUCKLES',
          '32MM STRAPS',
          '13MM STRAPS',
          '38MM BUCKLES',
          '42MM STRAPS',
        ],
      },
      {
        l2_name: 'BELTS STITCHED',
        list: ['OTHER BELTS', 'FASHION'],
      },
      {
        l2_name: 'CASHMERE SCARVES',
        list: ['OTHER CASHMERE', '70X70', '90X90', '140X140'],
      },
      {
        l2_name: 'ENAMEL',
        list: [
          'CLIC H OTHER',
          'OTHER ENAMEL',
          'BANGLES',
          'CLIC H BRAC',
          'CHARNIERE',
          'CLIC CLAC H BRAC',
        ],
      },
      {
        l2_name: 'EQUITATION',
        list: ['EQUITATION'],
      },
      {
        l2_name: 'FASHION JWL OTHER',
        list: ["CAGE D'H NECKLAC", 'OTHER FASH JWL', 'HORN', 'POP H NECKLACE'],
      },
      {
        l2_name: 'FEMME BAGS',
        list: [
          'BOLIDE',
          'OTHER LLG',
          'BI-MATERIAL OTHER',
          'JYPSIERE',
          'GARDEN PARTY',
          'EVELYNE',
          'LINDY',
          'PICOTIN',
        ],
      },
      {
        l2_name: 'FINE JEWELRY GOLD',
        list: ['RINGS', 'OTHER GOLD', 'NECKLACES', 'BRACELETS'],
      },
      {
        l2_name: 'FINE JEWELRY SILVER',
        list: [
          'GOLD/SILVER NECKLACES',
          'GOLD/SILVER OTHER',
          'GOLD/SILVER RINGS',
          'GOLD/SILVER BRACELETS',
          'SILVER BRACELETS',
          'SILVER NECKLACES',
          'SILVER RINGS',
          'SILVER OTHER',
        ],
      },
      {
        l2_name: 'FRENCH FESTIVAL PRODUCT',
        list: ['FRENCH FESTIVAL PRODUCT'],
      },
      {
        l2_name: 'GLOVES',
        list: ['GLOVE HOLDERS', 'GLOVES', 'HANKIES'],
      },
      {
        l2_name: 'HATS',
        list: ['HATS'],
      },
      {
        l2_name: 'Horizon',
        list: ['Others'],
      },
      {
        l2_name: 'LEATHER JEWELRY',
        list: [
          'OTHER LTHR JWL',
          'KELLY OTHER',
          'HAPI',
          'CDC',
          'KELLY DT',
          'KELLY DOG',
        ],
      },
      {
        l2_name: 'MEMORY-KEEPERS',
        list: ['REFILLS', 'COVER', 'OTHER MEMORY'],
      },
      {
        l2_name: 'MLLG',
        list: ['OTHER MLEATHER', 'BACKPACK', 'MESSENGER BAG', 'BRIEFCASE'],
      },
      {
        l2_name: 'MRTW',
        list: [
          'KNITS',
          'BOTTOMS',
          'LEATHER',
          'JACKETS',
          'TEES',
          'POLO',
          'WOVEN SHIRTS',
          'OTHER MRTW',
        ],
      },
      {
        l2_name: 'MSHOES',
        list: ['ATHLETIC', 'OTHER MSHOES'],
      },
      {
        l2_name: 'OTHER MENS SILK',
        list: ['LOSANGE', 'POCHETTE', 'MUFFLERS', 'MISC OTHER', 'BRODERIE'],
      },
      {
        l2_name: 'OTHER WOMENS SILK',
        list: [
          'MOUSSELINE',
          'EX-LIBRIS',
          'GAVROCHE',
          'SMALL TWILLY',
          'MISC OTHER',
          'MAXI TWILLY',
          'JERSEY',
          'BRODERIE',
          'TWILLON',
        ],
      },
      {
        l2_name: 'PARFUM',
        list: [
          'JARDIN SUR LE TOIT',
          'EAU DES MERVEILLES',
          'CLASSICS COLLECTION',
          'SOAPS',
          "JOUR D'HERMES",
          "TERRE D'HERMES",
          'HERMESSENCE',
          'JARDIN MONSIEUR LI',
          'COLOGNES COLLECTION',
          "VOYAGE D'HERMES",
          'OTHER FRAGRANCE',
          'BATH LINE',
          'JARDIN SUR LE NIL',
          'XMAS SETS',
          'LOCKS/REFILLS',
          'TRAVEL RETAIL SETS',
          'LEATHER CASES/REFILL',
          "TWILLY D'HERMES",
          'JARDIN SUR LA LAGUNE',
        ],
      },
      {
        l2_name: 'SCARF RINGS',
        list: ['SCARF RINGS'],
      },
      {
        l2_name: 'SLG',
        list: [
          'BEARN COLLECTION',
          'WALLETS OTHER',
          'KEY OTHER',
          'MISC OTHER',
          'MENS & MC2',
          'KELLY COLLECTION',
          'DOGON COLLECTION',
        ],
      },
      {
        l2_name: 'TIES',
        list: [
          'PRINTED CLASSIC',
          'WOVEN OTHER',
          'WOVEN FACONNEE',
          'WOVEN HEAVY SILK',
          'PRINTED FANTASY TWILL',
          'PRINTED OTHER TIES',
          'PRINTED HEAVY TWILL',
        ],
      },
      {
        l2_name: 'TWILL SCARVES',
        list: ['70X70 TWILL', '140X140 TWILL', '90X90 TWILL'],
      },
      {
        l2_name: 'VOYAGE',
        list: ['VOYAGE'],
      },
      {
        l2_name: 'WATCH',
        list: [
          'NON PRECIOUS WOMENS',
          'PRECIOUS MENS',
          'NON PRECIOUS MEN',
          'OTHER WATCH',
          'PRECIOUS WOMENS',
          'STRAPS',
        ],
      },
      {
        l2_name: 'WRTW',
        list: [
          'OTHER WRTW',
          'LEATHER',
          'TEES',
          'OUTERWEAR/JACKETS',
          'KNIT TOPS',
          'SCARF PRINT TOPS',
          'WOVEN BLOUSES',
          'PANTS',
          'SKIRTS',
        ],
      },
      {
        l2_name: 'WSHOES',
        list: ['SANDALS', 'ATHLETIC', 'OTHER WSHOES'],
      },
      {
        l2_name: 'Leather and Luggage',
        list: ['Luggage', 'MSLG'],
      },
      {
        l2_name: 'Skincare',
        list: [
          'Sun Products',
          'Body Products',
          'Cleansers',
          'Skincare Accessories',
          'Serums',
          'Toners',
          'Eye Treatment',
          'Face Moisturizers',
          'Skincare Mixed Sets',
          'Masks',
          'Repair Products',
          'Hair Products',
        ],
      },
      {
        l2_name: 'Fragrances',
        list: [
          'Room/Linen Sprays',
          'Body Moisturizer',
          'Coffrets',
          'Other Fragrance',
          'Bath & Shower',
          'Fragrance Accessories',
          'Hand Lotion',
          'Fragrance Singles',
          'Deodorant',
          'Fragrance Sets',
          'Diffusers',
          'Soap',
          'Home Accessories',
          'Aftershave/Balm',
          'Candles',
          'Home Fragrance',
        ],
      },
      {
        l2_name: 'Makeup',
        list: [
          'Lipstick',
          'Blushers',
          'Eye Color',
          'Makeup Accessories',
          'Makeup Mixed Sets',
          'Nail Enamel',
          'Powder',
          'Mascara',
          'Foundations',
        ],
      },
    ],
  },
  {
    l1_name: 'Food',
    sub: true,
    l2_categories: [
      {
        l2_name: 'Food',
        list: [
          'Baked Goods',
          'Sweets',
          'Nuts',
          'Fruits',
          'Coffee',
          'Condiments',
          'Tea',
          'Other Food',
          'Food Accessories',
          'Seafood',
          'Beverages',
          'Meat',
          'Wellbeing',
          'Chocolate',
        ],
      },
    ],
  },
  {
    l1_name: 'Gifts',
    sub: true,
    l2_categories: [
      {
        l2_name: 'Gifts',
        list: [
          'Toys',
          'Travel Accessories',
          'Earrings',
          'Hair Accessories',
          'Neck Jewelry',
          'Other Jewelry',
          'Rings',
          'Socks',
          'Tech Accessories',
          'Ties',
          'Umbrellas',
          'Wrist Jewelry',
          'Gloves',
          'Hats',
          'Kids Boots',
          'Kids Bottoms',
          'Kids Dresses',
          'Kids Drivers',
          'Kids Flats',
          'Kids Outerwear',
          'Kids Polo Shirts',
          'Kids Pumps',
          'Kids Resortwear',
          'Kids Sandals',
          'Kids Sneakers',
          'Kids Sweaters',
          'Kids Sweats',
          'Kids Tee Shirts',
          'Kids Underwear',
          'Kids Wovens',
          'Luggage',
          'M Belts',
          'M Boots',
          'M Bottoms',
          'M Drivers',
          'M Outerwear',
          'M Polo Shirts',
          'M Resortwear',
          'M Sandals',
          'M Shoes',
          'M Sneakers',
          'M Sweaters',
          'M Sweats',
          'M Tee Shirts',
          'M Underwear',
          'M Wovens',
          'MLLG',
          'MSLG',
          'Scarves',
          'Uni LLG',
          'Uni SLG',
          'W Belts',
          'W Boots',
          'W Bottoms',
          'W Dresses',
          'W Drivers',
          'W Flats',
          'W Outerwear',
          'W Polo Shirts',
          'W Pumps',
          'W Resortwear',
          'W Sandals',
          'W Sneakers',
          'W Sweaters',
          'W Sweats',
          'W Tee Shirts',
          'W Underwear',
          'W Wovens',
          'WLLG',
          'WSLG',
          'Fragrances',
          'Skincare',
          'Home Accessories',
          'Other Souvenirs',
          'Handcrafts',
          'Gifts',
          'Lighters',
          'Stationery',
          'Writing Instruments',
          'M Formalwear',
          'Makeup',
        ],
      },
    ],
  },
  {
    l1_name: 'SWT',
    sub: true,
    l2_categories: [
      {
        l2_name: 'Spirits',
        list: [
          'Vodka',
          'Tequila',
          'Rum',
          'Other Spirits',
          'Spirits Accessories',
          'American Whiskey',
          'Baijiu',
          'Gin',
          'Beer',
          'Liqueurs',
          'Sake',
          'Other Whiskey',
          'Scotch',
          'Single Malt',
          'Brandy',
        ],
      },
      {
        l2_name: 'Commercial Wine',
        list: [
          'Australia',
          'USA',
          'Italy',
          'France',
          'Other Wine',
          'South Africa',
          'New Zealand',
          'South America',
          'Other Europe',
          'Wine Accessories',
        ],
      },
      {
        l2_name: 'Prestige Wine',
        list: [
          'Prestige France',
          'Prestige Other',
          'Prestige USA',
          'Prestige New Zealand',
          'Prestige Australia',
          'Prestige Italy',
        ],
      },
      {
        l2_name: 'Cigars',
        list: ['Cigarillos', 'Accessories', 'Hand Made', 'Machine Made'],
      },
      {
        l2_name: 'Tobacco',
        list: ['Filter Cigarette', 'Non-Filter Tobacco', 'Tobacco Accessories'],
      },
    ],
  },
  {
    l1_name: 'WJA',
    sub: true,
    l2_categories: [
      {
        l2_name: 'Accessories',
        list: [
          'Uni SLG',
          'Uni LLG',
          'M Belts',
          'MSLG',
          'MLLG',
          'W Belts',
          'Luggage',
          'WSLG',
          'WLLG',
          'Writing Instruments',
          'Tech Accessories',
          'Gifts',
          'Lighters',
          'Scarves',
          'Watch Accessories',
          'Ties',
          'Hair Accessories',
          'Uni Sunglasses',
          'W Sunglasses',
          'Kids Sunglasses',
          'M Sunglasses',
          'Stationery',
          'Home Accessories',
          'Hats',
          'Socks',
          'Travel Accessories',
          'Umbrellas',
          'Gloves',
        ],
      },
      {
        l2_name: 'Jewelry',
        list: [
          'Wrist Jewelry',
          'Bridal Jewelry',
          'Other Jewelry',
          'Earrings & Head Jewelry',
          'Neck Jewelry',
          'Rings',
        ],
      },
      {
        l2_name: 'Watches',
        list: ['W Watches', 'Uni Watches', 'M Watches'],
      },
    ],
  },
];
